version: "3.7"

services:

    loadbalancer:
        image: migasfree/loadbalancer:${LOADBALANCER_TAG}
        
        ports:
            - 80:80
            - 443:443
            - 9999

        env_file:
            - ../config/env/globals
       
        deploy:
            replicas: 1

        networks:
            - mf_network

        volumes:
            - "../config/certs:/manualcerts"
            - certificates:/usr/local/etc/haproxy/certificates

    certbot:
        image: migasfree/certbot:${CERTBOT_TAG}
        env_file:
            - ../config/env/globals
        deploy:
            replicas: 1
        networks:
            - mf_network
        volumes:
            - certificates:/etc/certificates

networks:
    mf_network:
        external: true

volumes:
    certificates:
