#!/bin/bash

source ../config/env/general
source ../config/env/stack

_SERVICE=$1
_NUM=$2

docker service scale ${_SERVICE}=${_NUM}

_BALANCER=$(docker ps | grep loadbalancer | awk '{print $1}')

docker exec $_BALANCER reconfigure
