#!/bin/bash

function reload {
    CORE_CONTAINER=$(docker ps --filter name=core_loadbalancer --format "{{.ID}}")
    docker exec -ti $CORE_CONTAINER bash -c "reload"
}


source ../config/env/general
source ../config/env/stack

if [ "$1" = "mf" ]  # Only start stack mf
then
   docker stack deploy mf --compose-file migasfree.yml
   exit
fi

# NFS
./nfs-server

# NETWORK
docker network ls | grep ${STACK}_network
if [ $? -ne 0 ]
then
    docker network create --driver=overlay --attachable ${STACK}_network
fi

# Generates core.yml & migasfree.yml from templates
./templates/process

docker stack deploy --compose-file core.yml core

docker stack deploy --compose-file migasfree.yml ${STACK}

while true
do
    _STATUS=$(curl --write-out '%{http_code}' --silent --output /dev/null ${FQDN}/services/status)
    if [ "${_STATUS}" = "200" ]
    then
        echo "


                   ●                          ●●
                                             ●
         ●●● ●●    ●    ●●     ●●●     ●●●  ●●●●  ●●●  ●●●    ●●●
        ●   ●  ●   ●   ●  ●       ●   ●      ●   ●    ●   ●  ●   ●
        ●   ●  ●   ●   ●  ●    ●●●●    ●●    ●   ●    ●●●●   ●●●●
        ●   ●  ●   ●   ●  ●   ●   ●      ●   ●   ●    ●      ●
        ●   ●  ●   ●    ●●●    ●●●    ●●●    ●   ●     ●●●    ●●●
                          ●
                        ●●


        Visit: https://${FQDN}/services/status

        "
        break
    fi

    reload
    sleep 1
done
